version: '3'
services:
    debian:
      build: ./Debian
      ports:
      - "5002:5000"
      networks:
      - my_bridge
    centos:
      build: ./Centos
      ports:
      - "5000:5000"
      networks:
      - my_bridge

networks:
  my_bridge:
    driver: bridge
